version: "3.4"

services:
  database:
    container_name: project111_database
    image: postgres:14.5
    restart: always
    ports:
      - 5532:5432
    networks:
      - project111_net
    volumes:
      - project111_database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=project111
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  service-api:
    container_name: project111_service-api
    image: jeanbarcellos/project111_service-api:latest
    depends_on:
      - database
    ports:
      - 8080:8080
    networks:
      - project111_net
    environment:
      - PORT=8080
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=project111
      - DB_USER=postgres
      - DB_PASSWORD=postgres

networks:
  project111_net:
    name: project111_net
    driver: bridge

volumes:
  project111_database_data:
    name: project111_database_data
    driver: local
